GET FILE='sst2_covid19_dataset.sav'.
DATASET ACTIVATE DataSet1.

NPAR TESTS
  /K-S(NORMAL)=age sst2 spo2 ct_value lactate pao2
  /MISSING ANALYSIS.

FREQUENCIES VARIABLES=group gender dm ht dyslipidemia smoking cad obesity
  /ORDER=ANALYSIS.

MEANS TABLES=age sst2 spo2 ct_value lactate pao2 BY group
  /CELLS MEAN STDDEV MEDIAN COUNT.

CROSSTABS
  /TABLES=gender dm ht dyslipidemia smoking cad obesity BY group
  /STATISTICS=CHISQ
  /CELLS=COUNT COLUMN
  /COUNT ROUND CELL.

ONEWAY sst2 BY group
  /STATISTICS DESCRIPTIVES HOMOGENEITY
  /POSTHOC=BONFERRONI ALPHA(0.05).

NPTESTS
  /INDEPENDENT TEST (sst2) GROUP (group)
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE
  /CRITERIA ALPHA=0.05 CILEVEL=95.

USE ALL.
COMPUTE filter_case=(group=1).
FILTER BY filter_case.

CORRELATIONS
  /VARIABLES=sst2 spo2 ct_value lactate pao2
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

NONPAR CORR
  /VARIABLES=sst2 spo2 ct_value lactate pao2
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.

T-TEST GROUPS=ht(0 1)
  /MISSING=ANALYSIS
  /VARIABLES=sst2
  /CRITERIA=CI(.95).

T-TEST GROUPS=dm(0 1)
  /MISSING=ANALYSIS
  /VARIABLES=sst2
  /CRITERIA=CI(.95).

T-TEST GROUPS=dyslipidemia(0 1)
  /MISSING=ANALYSIS
  /VARIABLES=sst2
  /CRITERIA=CI(.95).

T-TEST GROUPS=smoking(0 1)
  /MISSING=ANALYSIS
  /VARIABLES=sst2
  /CRITERIA=CI(.95).

T-TEST GROUPS=cad(0 1)
  /MISSING=ANALYSIS
  /VARIABLES=sst2
  /CRITERIA=CI(.95).

T-TEST GROUPS=obesity(0 1)
  /MISSING=ANALYSIS
  /VARIABLES=sst2
  /CRITERIA=CI(.95).

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT sst2
  /METHOD=ENTER ht dm dyslipidemia smoking cad obesity spo2 pao2 lactate ct_value.

FILTER OFF.
USE ALL.
EXECUTE.
